jenkins:
  image: jenkins/jenkins:lts
  restart: always
  ports:
    - "8080:8080"
    - "5000:5000"
nginx:
  build: .
  restart: always
  ports:
    - "443:443"
  volumes:
    - ./site/:/etc/nginx/sites-available
    - ./ssl/:/etc/nginx/ssl
  links:
    - jenkins:jenkins
